#!/bin/bash
set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd code

echo "##" ; echo "##"
echo "## Checking go version..."
echo "##" ; echo "##"
go version; echo; echo

echo "##" ; echo "##"
echo "## Installing application dependencies..."
echo "##" ; echo "##"
grep github *.go | awk '{print $2}' | sed -e 's/"//g' | sort | uniq | xargs go get

echo "##" ; echo "##"
echo "## Running application tests..."
echo "##" ; echo "##"
go test -v
